services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=market'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
